### ISSUE TITLE
Error when using on CI

### ISSUE THREAD

**Issue by kylejm** [marcelofabri/xcpretty-json-formatter#5]
I'm getting the following error and stack trace when using this on our CI, Bitrise: 

```
/usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:18:in `read': No such file or directory @ rb_sysopen - xcpretty-json-formatter (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:18:in `class_from_path'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:26:in `load_custom_formatter'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:42:in `block (2 levels) in <top (required)>'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1427:in `call'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1427:in `block in parse_in_order'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:69:in `block in <top (required)>'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:917:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:27:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:27:in `<top (required)>'
	from /usr/local/bin/xcpretty:23:in `load'
	from /usr/local/bin/xcpretty:23:in `<main>'
```

Any idea what could be going on? I've tested locally and it seems to be fine.

**Comment by marcelofabri** [comment]
Are you sure you've installed the gem on CI? I've never used Bitrise, but could you paste the script/config file here?

**Comment by kylejm** [comment]
It's in my Gemfile, I just can't workout why it's not being picked up.

Script looks like this:
```
#!/bin/bash
            bundle install
            which xcpretty-json-formatter
            set -o pipefail && xcodebuild "-project" $BITRISE_PROJECT_PATH "-scheme" "Loot" "build" "test" "-destination" "platform=iOS Simulator,name=iPhone 6s Plus,OS=latest" | xcpretty "--color" -f 'xcpretty-json-formatter'
            bundle exec danger
```

Gemfile:

```
source 'https://rubygems.org'

gem "danger", git: "https://github.com/kylejm/danger.git", branch: "git-mergebase-fix"
gem "danger-xcodebuild"
gem "danger-todoist"
gem "danger-prose"
gem "danger-swxftlint"
gem "xcpretty-json-formatter"
```

Gemfile.lock:
```
GIT
  remote: https://github.com/kylejm/danger.git
  revision: 6707ca4a402535e257024aee41b07df769d5572f
  branch: git-mergebase-fix
  specs:
    danger (3.2.1)
      claide (~> 1.0)
      claide-plugins (> 0.9.0)
      colored (~> 1.2)
      cork (~> 0.1)
      faraday (~> 0.9)
      faraday-http-cache (~> 1.0)
      git (~> 1)
      gitlab (~> 3.7.0)
      kramdown (~> 1.5)
      octokit (~> 4.2)
      terminal-table (~> 1)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.4.0)
    claide (1.0.0)
    claide-plugins (0.9.1)
      cork
      nap
      open4 (~> 1.3)
    colored (1.2)
    cork (0.2.0)
      colored (~> 1.2)
    danger-plugin-api (1.0.0)
      danger (> 2.0)
    danger-prose (2.0.3)
      danger
    danger-swiftlint (0.2.1)
      danger
    danger-todoist (1.0.1)
      danger-plugin-api (~> 1.0)
    danger-xcodebuild (0.0.3)
      danger (~> 3.0)
    faraday (0.9.2)
      multipart-post (>= 1.2, < 3)
    faraday-http-cache (1.3.1)
      faraday (~> 0.8)
    git (1.3.0)
    gitlab (3.7.0)
      httparty (~> 0.13.0)
      terminal-table
    httparty (0.13.7)
      json (~> 1.8)
      multi_xml (>= 0.5.2)
    json (1.8.3)
    kramdown (1.12.0)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    nap (1.1.0)
    octokit (4.3.0)
      sawyer (~> 0.7.0, >= 0.5.3)
    open4 (1.3.4)
    rouge (1.11.1)
    sawyer (0.7.0)
      addressable (>= 2.3.5, < 2.5)
      faraday (~> 0.8, < 0.10)
    terminal-table (1.7.2)
      unicode-display_width (~> 1.1.1)
    unicode-display_width (1.1.1)
    xcpretty (0.2.2)
      rouge (~> 1.8)
    xcpretty-json-formatter (0.1.0)
      xcpretty (~> 0.2, >= 0.0.7)

PLATFORMS
  ruby

DEPENDENCIES
  danger!
  danger-prose
  danger-swiftlint
  danger-todoist
  danger-xcodebuild
  xcpretty-json-formatter

BUNDLED WITH
   1.12.5
```

**Comment by marcelofabri** [comment]
Could you try changing to `bundle exec xcpretty` in your script?

**Comment by kylejm** [comment]
Still no luck 😞. Slightly different stack trace though:
```
Errno::ENOENT: No such file or directory @ rb_sysopen - xcpretty-json-formatter
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:18:in `read'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:18:in `class_from_path'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/lib/xcpretty.rb:26:in `load_custom_formatter'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:42:in `block (2 levels) in <top (required)>'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1427:in `call'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1427:in `block in parse_in_order'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1383:in `catch'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1383:in `parse_in_order'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1377:in `order!'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1469:in `permute!'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:1491:in `parse!'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:69:in `block in <top (required)>'
  /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/optparse.rb:917:in `initialize'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:27:in `new'
  /usr/local/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.2/bin/xcpretty:27:in `<top (required)>'
```

**Comment by marcelofabri** [comment]
What about?

    bundle exec xcpretty -f `bundle exec xcpretty-json-formatter`

Sorry to make you do all these tests 😬

**Comment by marcelofabri** [comment]
Wait, I see now that you've used `'xcpretty-json-formatter'` in your script (with single quotes). This should be in backticks (\`)

**Comment by kylejm** [comment]
IT WORKED!!!! Thank you so much! Is that a thing known with using `bundle`? 😂 

P.S. if you haven't worked it out, I'm a complete n00b at Ruby.

**Comment by marcelofabri** [comment]
I don't think it's related to using `bundler`, but how custom formatters are implemented in xcpretty: https://github.com/kattrali/xcpretty-travis-formatter#how-it-works
